### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by brandondb1** [pschmitt/pschmitt#1]
Hello, a couple of things...sorry to put this here but you didn't have contact info...

1. your certificate on your web site is broken somehow, so I couldn't see your resume.
2. for the Home Assistant Avahi Reflector, do you think it would be possile to add .service files?  I've played with Avahi quite a bit, but I have to say I'm foggy on Docker so I don't know exactly how one would do that...I've been trying to get MQTT devices to reliably find HomeAssistant without hardwiring the IP.  They will find an avahi MQTT service on another device, but it's not practical to have a second Pi running just avahi to point them to Home Assistant.

Cheers!

Brandon

**Comment by pschmitt** [comment]
Hi!

1. Thanks for the hint. I'll look into it.
2. Why don't you open an issue over on [pschmitt/home-assistant-addons](https://github.com/pschmitt/home-assistant-addons)? Quick hint though: the intended purpose of this addon is to reflect mDNS from one network to another and probably won't ever be able to serve your usecase.
